"use strict";

const request = require("request")
    , querystring = require("querystring")
    ;

module.exports = class LoadWalletAPI {
    /**
     * LoadWalletAPI
     * Creates the instance of the `LoadWalletAPI` class.
     *
     * @name LoadWalletAPI
     * @function
     * @param {Object} options An object containing:
     *
     *  - `username` (String): LoadWallet API username credentials (mandatory).
     *  - `password` (String): LoadWallet API password credentials (mandatory).
     *  - `host` (String): LoadWallet api host (Optional default: `https://api.loadwallet.com`).
     *  - `timeout` (Integer): integer containing the number of milliseconds to wait for a server to send response headers (and start the response body) before aborting the request.  (Optional default: 60000).
     */
    constructor (options) {

        this.username = options.username;
        this.password = options.password;
        this.host = options.host || "https://api.loadwallet.com";
        this.timeout = options.timeout || 60*1000;
        this.request = request;
    }

    /**
     * topupd
     * Send topup request to LoadWalletAPI
     *
     * @name topup
     * @function
     * @param {Object} data. To be passed by the client. (mandatory)
     * @param {Function} cb The callback function.
     */
    topup (data, cb) {
        return this._request({
            url: "reloads",
            method: "post",
            data: data
        }, cb);
    }

    /**
     * balanceInquiry
     * Get loadwallet or account balance
     *
     * @name balanceInquiry
     * @function
     * @param {Function} cb The callback function.
     */
    balanceInquiry (cb) {
        return this._request({
            url: "accounts/balance"
        }, cb);
    } 

    /**
     * getTopUp
     * Get topup status
     *
     * @name getTopUp
     * @function
     * @param {String} tranId Unique alphanumeric id of request. Generated by the client during topup request. (mandatory)
     * @param {Function} cb The callback function.
     */
    getTopUp (tranId, cb) {
        return this._request({
            url: "reloads/"+tranId
        }, cb);
    } 

    /**
     * getProducts
     * Get Product Catalog
     *
     * @name getProducts
     * @function
     * @param {Function} cb The callback function.
     */
    getProducts (cb) {
        return this._request({
            url: "product/catalog"
        }, cb);
    }

    /**
     * _request
     * Low level function for making requests to the API endpoints.
     *
     * @name _request
     * @function
     * @param {Object} options An object containing the following fields:
     *
     *  - `url` (String): The api endpoint.
     *  - `method` (String): The request method (default: `get`).
     *  - `query` (Object): The query object.
     *  - `data` (Object): The POST data object.
     *  - `version` (String): API Version. If not specified your pinned verison is used.
     *
     * @param {Function} cb The callback function.
     */
    _request (options, cb) {
        let _url = options.url
          , method = options.method || "get"
          , query = options.query || {}
          , data = options.data
          , timeout = this.timeout
          , qs = querystring.stringify(query)
          , removeTrailingSlash = options.removeTrailingSlash || false
          , url = this.host + "/" + _url + (removeTrailingSlash ? "" : "/") + (qs ? "?" + qs : "")
          ;

        return request({
            url: url
          , method: method
          , timeout: timeout
          , headers: {
             'Content-Type': 'application/json',
             'Authorization': 'Basic ' + (new Buffer(this.username+':'+this.password).toString('base64')) 
            }
          , json: data ? data : true
        }, (err, res) => {
            if (res && res.body ) 
                cb(err, res.body, res); 
            else 
                cb(err, null, res)
        })
    }
};